<?php

arch('controllers do not depend on storage implementations directly')->todo();
arch('middleware does not depend on storage implementations directly')->todo();
arch('storage implementations do not depend on HTTP layer')->todo();
arch('normalizer does not depend on HTTP, controllers, or middleware')->todo();
arch('transport depends on CaptureService but not on concrete storage')->todo();
arch('service provider is the only place registering transport and bindings')->todo();
arch('tests must not reference internal storage paths directly (use contracts)')->todo();
arch('no classes use facades in constructors (constructor DI only)')->todo();
arch('public API namespace does not reference framework test utilities')->todo();
arch('no production code uses dd(), dump(), ray(), or var_dump')->todo();
arch('no class in package uses hard-coded absolute paths')->todo();
arch('only service provider reads config directly; other layers receive settings via DI')->todo();
arch('Http controllers only used from Routes and never by other domains')->todo();
arch('Middleware only referenced in route/middleware stacks')->todo();
arch('Transport layer only referenced by mail manager / service provider')->todo();
arch('Storage implementations live in Infrastructure namespace and implement Contracts\\MessageStore')->todo();
arch('Domain services depend on Contracts, not concrete implementations')->todo();
arch('Facades (if any) only reference container bindings (no new-ing concretes)')->todo();
arch('package code must not depend on external network clients')->todo();
arch('storage must not depend on Illuminate\\Http or Symfony\\HttpFoundation')->todo();
arch('domain and contracts must not depend on Illuminate\\View, Illuminate\\Routing')->todo();
arch('controller must not depend on Illuminate\\Mail or Transport internals')->todo();
arch('all middleware names end with Middleware')->todo();
arch('all controllers end with Controller')->todo();
arch('all contracts interfaces end with interface name or reside in Contracts namespace')->todo();
arch('config keys use prefix "inbox." only')->todo();
arch('tests reside in /tests and use Pest test files ending with Test.php')->todo();
arch('classes have strict_types declaration (if you adopt it)')->todo();
arch('no class suppresses PHPStan baseline for level >= your target')->todo();
arch('no todo/fixme comments in src (or only allowed pattern)')->todo();
